version: '3.9'
services:
  blockscout:
    depends_on:
      - nitro
    image: offchainlabs/blockscout:v1.0.0-c8db5b1
    restart: always
    links:
      - postgres:database
    command:
      - /bin/sh
      - -c
      - |
        bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
        node init/install.js postgres 5432
        bin/blockscout start
    environment:
      ETHEREUM_JSONRPC_VARIANT: 'geth'
      ETHEREUM_JSONRPC_HTTP_URL: http://nitro:8449/
      ETHEREUM_JSONRPC_TRACE_URL: http://nitro:8449/
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      DATABASE_URL: postgresql://postgres:@postgres:5432/blockscout
      ECTO_USE_SSL: "false"
      NETWORK: ""
      SUBNETWORK: "Arbitrum Local"
      BLOCKSCOUT_VERSION: "Arbitrum 0.0.1"
      PORT: 4000
    ports:
      - "127.0.0.1:4000:4000"

  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  nitro:
    image: ghcr.io/fhenixprotocol/nitro/fhenix-node:v0.0.5-beta1
    ports:
      - "127.0.0.1:8449:8449"
      - "127.0.0.1:9642:9642"
    volumes:
      - "./config:/home/user/.arbitrum"
      - "./keys:/home/user/keys"
    command: --conf.file /home/user/.arbitrum/nodeConfig.json --node.feed.output.enable --node.feed.output.port 9642 --http.api net,web3,eth,txpool,debug --node.seq-coordinator.my-url ws://node:8449 --graphql.enable --graphql.vhosts * --graphql.corsdomain * --metrics --metrics-server.addr 0.0.0.0 --metrics-server.port 6070

  das-server:
    image: ghcr.io/fhenixprotocol/nitro/fhenix-node:v0.0.5-beta1
    entrypoint: [ "/bin/bash", "/das-server.sh" ]
    volumes:
      - "./config:/home/user/.arbitrum"
      - "./das-server.sh:/das-server.sh"
      - "./fhe_keys:/home/user/keys"
    ports:
      - "9876:9876"
      - "9877:9877"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

